alias:
  # Main
  - "gemini:openrouter/google/gemini-2.5-pro-preview"
  - "claude:openrouter/anthropic/claude-sonnet-4"
  # Weak
  - "devstral:openrouter/mistralai/devstral-small:free"
  - "chat:openrouter/deepseek/deepseek-r1-0528-qwen3-8b:free"
  - "r1:openrouter/deepseek/deepseek-chat-v3-0324:free"
model: "claude"
weak-model: "devstral"
show-model-warnings: false
dark-mode: true
