# model: "openrouter/deepseek/deepseek-chat"
model: "openrouter/google/gemini-2.5-pro-preview"
weak-model: "openrouter/deepseek/deepseek-r1-0528-qwen3-8b:free"
show-model-warnings: false
dark-mode: true
