# model: "openrouter/google/gemini-2.5-pro-preview"
model: "openrouter/anthropic/claude-sonnet-4"
# weak-model: "openrouter/deepseek/deepseek-r1-0528-qwen3-8b:free"
weak-model: "deepseek/deepseek-chat-v3-0324:free"
show-model-warnings: false
dark-mode: true
