[colors.primary]
background = "0x000000"
foreground = "0xff0000"

[colors.normal]
black   = "#000000"  # Black
red     = "#CC0000"  # Red
green   = "#4E9A06"  # Green
yellow  = "#C4A000"  # Yellow
blue    = "#3465A4"  # Blue
magenta = "#75507B"  # Magenta
cyan    = "#06989A"  # Cyan
white   = "#D3D7CF"  # White

[colors.bright]
black   = "#555753"  # Dark gray
red     = "#EF2929"  # Light red
green   = "#8AE234"  # Light green
yellow  = "#FCE94F"  # Light yellow
blue    = "#729FCF"  # Light blue
magenta = "#AD7FA8"  # Light magenta
cyan    = "#34E2E2"  # Light cyan
white   = "#EEEEEC"  # Light gray

[window]
opacity = 0.9
decorations = "None"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }

# The size of the font.
size = 11.0
