#!/usr/bin/env sh
DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

docker run --rm -v "$PWD:/src" -w /src koalaman/shellcheck:v0.10.0 \
  *.sh \
  dot-sync \
  --severity=style \
  --color=always
